apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempconverter
  labels:
    app: tempconverter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tempconverter
  template:
    metadata:
      labels:
        app: tempconverter
    spec:
      containers:
      - name: tempconverter
        image: codetome1503/tempconverter:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          value: "user"
        - name: DB_PASS
          value: "pass"
        - name: DB_HOST
          value: "db-service"
        - name: DB_NAME
          value: "tempconvert"
        - name: STUDENT
          value: "Tomislav Keščec"
        - name: COLLEGE
          value: "Algebra University College"
